name = "siglum-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[routes]]
pattern = "packages.siglum.org/*"
zone_name = "siglum.org"

[[routes]]
pattern = "ctan-proxy.siglum.org/*"
zone_name = "siglum.org"

# R2 bucket binding for bundles
[[r2_buckets]]
binding = "BUNDLES"
bucket_name = "siglum-bundles"
